name: parliamo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adobe_xd:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  flutter_swiper:
  firebase_storage:
  http:
  flutter_pdfview:
  path_provider:
  syncfusion_flutter_pdfviewer:
  google_sign_in:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - images/back.png
    - images/logo.png
    - images/gplus.png
    - images/tt.png
    - images/fb.png
    - images/add.png
    - images/email.jpg
    - images/firstName.png
    - images/password.png
    - images/add.png
    - images/form.png
    - images/relation.png
    - images/name.png
    - images/age.png
    - images/blood.png
    - images/weight.png
    - images/userMale.png
    - images/userFemale.png
    - images/gender.png
    - images/whiteLiver.png
    - images/whiteKidney.png
    - images/whitelungs.png
    - images/whiteRBC.png
    - images/whiteAllergy.png
    - images/reports.png
    - images/remarks.png
    - images/az.png
    - images/conditions.png
    - images/doctor.png
    - images/drawer.jpg
    - images/tests.png
    - images/lifecycle.png
    - images/lungsfinal.png
    - images/diagnose.png
    - images/greenSmiley.png
    - images/sad.png
    - images/Coughing.png
    - images/Diarrhea.png
    - images/Fever.png
    - images/Headache.png
    - images/Muscle Pain.png
    - images/Vomiting.png
    - images/neutral.png
    - images/google.png
    - images/team.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: 'Segoe UI'
      fonts:
        - asset: fonts/Segoe Ui.ttf
    - family: 'Franklin Gothic'
      fonts:
        - asset: fonts/FranklinGothic.ttf
    - family: 'Arial'
      fonts:
        - asset: fonts/Arial.TTF
    - family: 'Javanese Text'
      fonts:
        - asset: fonts/javanese.ttf
    - family: 'Constantia'
      fonts:
        - asset: fonts/constania.ttf
    - family: 'Bookman Old Style'
      fonts:
        - asset: fonts/BookManOldStyle.TTF

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
